"""empty message

Revision ID: 1baa18fef687
Revises: 3bc4935867d3
Create Date: 2015-06-02 01:51:15.997758

"""

# revision identifiers, used by Alembic.
revision = '1baa18fef687'
down_revision = '3bc4935867d3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
