"""empty message

Revision ID: 3bc4935867d3
Revises: 21196496a754
Create Date: 2015-06-02 01:48:10.071134

"""

# revision identifiers, used by Alembic.
revision = '3bc4935867d3'
down_revision = '21196496a754'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
